### ISSUE TITLE
Acknowledge of consume jms msg  in kafka producer callback is UNRELIABLE 

### ISSUE THREAD

**Issue by zhenik** [sysco-middleware/ibmmq-kafka-transfer#1]
Lose of data and unreliable. 
```java
producer.send(new ProducerRecord<>(topic, null, payload),
                (recordMetadata, e) -> {
                  if (e==null) {
                    try {
                      receivedMessage.acknowledge();
                    } catch (JMSException ex) {
                      ex.printStackTrace();
                      int i = 5/0; // :)
                    }
                  }
                });
```

______

This part should be implemented with blocking construct `producer.send().get()` because of jms transaction.

**Comment by jeqo** [comment]
Callback seems a bit flaky: not action is taking when `e!=null`. 

If you use session mode where client ack:

```java
        final JMSContext context = connectionHelper.getContext().createContext(JMSContext.SESSION_TRANSACTED); //or CLIENT_ACK
```

Messages won't get lost, as consumer will wait until message has been acknowledge.

I recommend the following paths:

- Compare the following approaches performance-wise: blocking with `get` vs. acknowledge callback with manual ACK session mode.
- Independent from the results an additional way to increase throughput, we can start instances on parallel.

PS: would be good to add steps to reproduce if there is claim of something not working. Currently I'm sending to a stopped cluster to reproduce (fast data container is a bit heavy ~1GB)

**Comment by zhenik** [comment]
I will provide example later.

**Comment by zhenik** [comment]
I provided [example](https://github.com/sysco-middleware/ibmmq-kafka-transfer/commit/9137a65feebd4842cc40620b10288b2b08faffbd#diff-88e3971441fe385e3eb48a04b7b4d22a) and played with it. I found narrow place in my code. 

I think it was not use immutable variables when work with a Kafka Producer and its callback.
I set all variables to `final` and test it. Works fine, I will continue in dev of NT.
